-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgoROEOqToyIS+0R6v
dpNQHJEqHxsuDexjHRJ+FfMlgoqgCgYIKoZIzj0DAQehRANCAAQO55Q8wfo+0wBR
fB/CklVvWk15aVSUzdFyf+GkTySGE22EUY90fJ9c6vB5j8uYHg+x7Z//2aLrZRr6
KG/DFW7D
-----END PRIVATE KEY-----